// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOAP2JSON.Data;

namespace SOAP2JSON.Migrations
{
    [DbContext(typeof(ValuesContext))]
    [Migration("20191108142413_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SOAP2JSON.Model.LogData1", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime>("InsertDate");

                    b.HasKey("Id");

                    b.ToTable("LogData1s");
                });

            modelBuilder.Entity("SOAP2JSON.Model.LogData2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate");

                    b.Property<int>("LogData1Id");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("LogData1Id");

                    b.ToTable("LogData2s");
                });

            modelBuilder.Entity("SOAP2JSON.Model.LogData2", b =>
                {
                    b.HasOne("SOAP2JSON.Model.LogData1", "LogData1")
                        .WithMany("LogData2s")
                        .HasForeignKey("LogData1Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
